# 1: Introduction to array

In [ ]:
### We always have to import packages to start working with built in packages

import numpy as np

In [4]:
### Introducing arrays

# So what is array? Array is also like a list; BUT list can stores mutiple types of data,
# Arrays can store one type of data types

# Let me show you

this_is_list = ["Fedrick", 19, False] # We have different types of data in this list

# Now let's check what is the type of this_is_a_list

type(this_is_list)

# Is a list:

list

In [10]:
# let's see now if we use array

this_is_array = np.array(["Fedrick", 19, False]) # So what happen here is that I have to use array function in numpy
# So in order to use array function in numpy, I have to np.array()
# np.array() is the function and within this function I'll have a list of things, therefore I use [] in np.array()
# => np.array([1,2,3])

# This is also the same as:
# this_is_array = np.array(this_is_list)

# Now, let's print this
print(this_is_array)


['Fedrick' '19' 'False']


In [7]:
# Look what happen?
# All 3 of the elements have ''
# Now, let's see what is this data type

type(this_is_array)

# Is an array:

numpy.ndarray

# 2: Application of arrays

In [12]:
# So what is the different between arrays and list
# > list is a list, but arrays can do computational works

# Let me show you waht I mean

a = [43, 9, 10, 11, 55] 
b = [4, 24, 100, 2, 11]

# Here is two list, let's combine them

c = a + b
print(c)

[43, 9, 10, 11, 55, 4, 24, 100, 2, 11]


In [14]:
# YOU SEE WHAT IS THIS????
# This is not not addition between a and b, is just a combination
# So how to do addition, we need to make it array!

# Let's make it array:

a_array = np.array(a)
b_array = np.array(b)

# Now they are array, now, let's do addition

c_array = a_array + b_array
print(c_array)

# LOOK! Addition:

[ 47  33 110  13  66]


# 3: Array and list similarity

In [19]:
# Now, lets harvest data from the arrays using indexing:

# We want the data: 33, 110 and 13 from the arrays, how can we print this?
# We can do this by using indexing:

middle_three = c_array[1:4] # WHY 4??? Because the index work as [inclusive: exclusive], 
# So means include element 1 up to element 4

print(middle_three)

[ 33 110  13]


In [24]:
# If I want only the last two elements?

last_two = c_array[-2: ] # Why is there an empty space after [-2: ]?
# It means from the element -2 until end

print(last_two)

[13 66]


In [27]:
# If I want to print every other element in c_array?

every_other = c_array[0: :2] # WHAT IS THIS?????
# This means from element 0, all the way until the end, skip 2

print(every_other)

[ 47 110  66]


In [30]:
# NOW, if there is a list in a list?
# It is called a nested list

nested = np.array([[1, 2, 3, 4],[10, 9, 8, 7]]) # Why 2 sqaure brackets?
# What happen here is [[list 1], [list 2]]: list in a list

print(nested)

[[ 1  2  3  4]
 [10  9  8  7]]


# 4: Methods in array

In [32]:
### Shape

# We can see the shape of array using np.shape function

np.shape(nested) 

# This mean (Row x Column)

(2, 4)

In [33]:
### Size 

# We can see the size using np.size function (Row x Column)

np.size(nested)

8

In [35]:
### Transpose

# We can transpose using np.transpose, it is very straight forward!

nested_transpose = np.transpose(nested)
print(nested_transpose)

# The Row become Column, and the Column become Row

[[ 1 10]
 [ 2  9]
 [ 3  8]
 [ 4  7]]


In [43]:
# Now, it is already transposed, how can I get the data [1, 2, 3, 4] as small?

small = nested_transpose[:,0] # What is this?
# This is [Row, Column]
# So it means [for all the rows, give me first column]

print(small)

[1 2 3 4]


In [46]:
# If I want 2nd row and 3rd row data for both row and column?

nested_23 = nested_transpose[1:3,:]
# [give me row 1 to 3, for all the columns]

print(nested_23)

[[2 9]
 [3 8]]


# 5: Copying arrays

In [47]:
x = np.array([1, 2, 3]) # Let's say we have this array
y = x
y[0] = 100 # y index first element, become 100: so 1 become 100

print(y)

[100   2   3]


In [48]:
# y will be fine, but x will not be [1, 2, 3], let's see

print(x)

[100   2   3]


In [50]:
# How to solve this?

f = np.array([1, 2, 3])
g = f.copy() # Using .copy() function

g[0] = 100

print(g); print(f)

# Solved:

[100   2   3]
[1 2 3]


# 6: Mathematics with array

In [52]:
# let's print nested_transpose

print(nested_transpose)

[[ 1 10]
 [ 2  9]
 [ 3  8]
 [ 4  7]]


In [58]:
# So now we want to get maximum in each column
# We use np.max function to get the maximum

np.max(nested_transpose, axis =0)

# axis = 0 for column
# axis = 1 for row
# no axis = whole sample

array([ 4, 10])

In [59]:
# We can do summation for each row too

np.sum(nested_transpose, axis = 0)

array([10, 34])

In [60]:
# And we have other function such as

# np.mean for mean
# np.std for standard deviation

# Boolean array

In [61]:
# Let's create a data

data = np.array([34, 23, 142, 9, 66])

# Now find the mean of the data

data_mean = np.mean(data)

# Let's create a boolean array to see if the elements in data are greater than the average 

boolean_data = data_mean < data
print(boolean_data)

[False False  True False  True]


In [63]:
# Now, let's find which number are more than average

print(data[boolean_data])

[142  66]
